### ISSUE TITLE
high ram usage when downloading from a list

### ISSUE THREAD

**Issue by Beno-kun** [Nandaka/DanbooruDownloader#146]
like the title said,i maxed out my 8gb ram when downloading from an xml list which i intended to continue downloading from yesterday...it causes my pc to stutter heavily...is it normal for the program to use THAT much ram?
I hope that issue will be resolved..and unfortunately no screenshot because the program now has a hard time responding..

**Comment by Nandaka** [comment]
can you upload the xml list?

**Comment by Beno-kun** [comment]
[continue lucoa dl.zip](https://github.com/Nandaka/DanbooruDownloader/files/1440993/continue.lucoa.dl.zip)
sorry for zipping the xml file but i was unable to upload the xml file directly due to github not supporting it for some reason..but here it is...

**Comment by Beno-kun** [comment]
![damn son](https://user-images.githubusercontent.com/33324801/32379376-5bed0344-c0e8-11e7-88be-efe6e355d407.jpg)
and here's a screenshot of it...good god what in heavens name is that...its maxing out all those 8gb ram...send..help..

**Comment by GiRaFa-SM** [comment]
Looks like if you activate some options and do specific tasks on this program it becomes stuck and consumes a lot of memory. 

I had issues while i had colored tags and when i tried to load a list in the main tab it took a lot of time to do it.

When i tried to load a list saved previously it caused some memory leaks too. It stopped only after disabling colored tags. Still, some options increase memory load.

There are other issues made by me regarding tags, give a look at them, dev posted its settings there, it may solve your problem.

**Comment by JMM72** [comment]
This seems related to an issue I reported a while ago (can't fin the issue link right now). Using batch download consumed huge amounts of RAM due to DD not releasing memory in a timely fashion, although Nandaka made it explicitly clear the used memory.  Win 7 64 bits, reinstalled recently and this still happens. The problem is that Nandaka can't reproduce the bug, it seems it only happens on certain cases and as an ex-dev I know it's hard to fix a bug you can't reproduce yourself.

In my case, I just stop the batch jobs after 20-30, and then resume. As soon as the first batch job starts, all old memory is released and the program. It's not a fix, just a workaround.

**Comment by novascotia131** [comment]
@Nandaka 
Personally I think the high memory usage is due to the DOM parser having to create new html documents for every tag in SankakuComplexParser.cs ReparseTags function. Some computers will have their garbage collector free up HtmlDocument objects as the for loop iterates faster than others, while others are less aggressive with their garbage collector and memory begins to bloat.

In the for loop where you iterate over each HtmlNode in tagsElement, I would just get the attribute from "tags" straight away.

>var cls = tags.Attribute["class"].value

**Comment by Nandaka** [comment]
updated in https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20181029

**Comment by novascotia131** [comment]
I shouldn't speak with such finality. Now that I'm testing out the downloader, there still seems to be memory being held up by the application between batches permanently. On the upside though, memory usage doesn't increase during batches.

When I have more time I will profile FormMain.cs and see what is actually taking up so much memory. I have a suspicion that at the start of every batch the numerous calls to DownloadFile/DownloadFileAsync/DownloadString are still in scope while the application runs.
