### ISSUE TITLE
batch downloader doesn’t leech all images

### ISSUE THREAD

**Issue by maskkulin** [Nandaka/DanbooruDownloader#55]
when i’m downloading many pics this happens: http://i.imgur.com/TFAxlTe.png

**Comment by Nandaka** [comment]
upload the log file to the pastebin.

**Comment by maskkulin** [comment]
http://pastebin.com/PB6R59F0

**Comment by Nandaka** [comment]
From the log file:

> Der Remoteserver hat einen Fehler zuruckgegeben: (429) Too many requests - please slow down

Sankaku apply download limit from the server, need to wait or increase the delay between download (set the settings on Settings tab -> Batch Delay. Most of your issue is because of this.

> Es konnte kein geschutzter SSL/TLS-Kanal erstellt werden

For some reason the secure connection cannot be made, either network issue or server issue.

**Comment by maskkulin** [comment]
thanks, it works now :)
